name: dann_ijcai23
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - gym=0.21.0
  - matplotlib=3.5.2
  - matplotlib-base=3.5.2
  - numpy=1.23.1
  - numpy-base=1.23.1
  - opencv=4.6.0
  - pillow=9.2.0
  - pip=22.2.2
  - py-opencv=4.6.0
  - python=3.9.13
  - pytorch=1.12.1
  - pytorch-mutex=1.0
  - torchvision=0.13.1

